### ISSUE TITLE
Possible Error in Gaussian Kernel Function (and question about sigma)

### ISSUE THREAD

**Issue by rajicon** [gallantlab/pyrcca#16]
https://github.com/gallantlab/pyrcca/blob/bc10a59a64f0c981b2f94522e1231d7bbc666112/rcca.py#L367

I believe there is an error here. Due to lack of parenthesis, it multiplies times gausigma ** 2 instead of dividing. I think it should be:

kernel = np.exp((-pairwise_dists ** 2) / (2*gausigma ** 2))

However, I'm not sure, so please double check this if possible.

In addition, I had a question about gausigma.  Is it possible for each set of vectors being aligned to have their own sigma?  I read a paper that suggested a good sigma was the pairwise distance between data points, and I assume this means each would have their own sigma.  However, looking at the implementation here, it seems that there is only one sigma, so I thought I would ask about it.

**Comment by theohj826** [comment]
I also came across this as well. It seems like the gaussian and polynomial kernels are not working correctly for me on synthetic datasets (rotations are off and canonical components are flipped).

**Comment by nbilenko** [comment]
Hello, thank you both for pointing this out. This is indeed an error with the parentheses. I'm currently working on a code refactor that will fix this error and add tests to prevent similar issues in the future. In the meantime, if you would like to, please feel free to submit a PR with a fix.

**Comment by TomDLT** [comment]
Fixed in #22
