### ISSUE TITLE
PyPI package

### ISSUE THREAD

**Issue by rgerkin** [gallantlab/pyrcca#18]
I just started using this for a project but it would be easier to share as a pip-installable package.  Would you be interested in having me modify accordingly?

**Comment by TomDLT** [comment]
Yes, it would be great to have the package on PyPI (cf #17).

It would mean reorganizing the files into a proper python package (adding `__init__.py`, `setup.py`, etc.). Do you want to do it ?

**Comment by rgerkin** [comment]
@TomDLT I already uploaded it to PyPI as a test, so I can yank it (freeing up the name for you to upload it) or I can add you as another owner (and then you can remove me, if you'd like). What is your PyPI username?

**Comment by TomDLT** [comment]
My PyPI username is `tomdlt`

**Comment by rgerkin** [comment]
Done.  I uploaded as 0.1 with the version I submitted in the PR, so you can bump the version number and upload a new one.  Have you done that before (sdist upload and twine)?

**Comment by TomDLT** [comment]
Done, I updated the readme, and uploaded the new version to PyPI.
Thanks a lot !
