### ISSUE TITLE
Support h5py>=3.0

### ISSUE THREAD

**Issue by afrendeiro** [gallantlab/pyrcca#23]
The `.value` attribute in h5py is deprecated and has been removed in 3.0 and above:
https://docs.h5py.org/en/stable/whatsnew/2.1.html#dataset-value-property-is-now-deprecated

Currently the `load` function of the model uses the older `.value` syntax to retrieve the model values which makes `load` fail in newer h5py versions.

**Comment by TomDLT** [comment]
Closed in #24
